version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - populous

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - populous
    depends_on:
      - elasticsearch

#  logstash2:
#    build:
#      context: logstash2/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    volumes:
#      - ./logstash2/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#      - ./logstash2/pipeline:/usr/share/logstash/pipeline:ro
#      - ./logstash2/logs:/usr/share/logstash/logs:ro
#    ports:
#      - "9601:9600"
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      - populous
#    depends_on:
#      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - populous
    depends_on:
      - elasticsearch

  tweeter-streams:
    build:
      context: tweeter-streams/
    volumes:
      - ./tweeter-streams/logs/:/var/log/tweeter-streams/
#      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
#    ports:
#      - "5601:5601"
    networks:
      - populous
    depends_on:
      - elasticsearch

  filebeat:
    build: filebeat/
    volumes:
      #- ./filebeat/config:/etc/filebeat
      - ./tweeter-streams/logs/:/var/log/tweeter-streams/
    networks:
      - populous
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch

networks:

  populous:
    driver: bridge
