version: '2'

services:

  flink-jobmanager:
    image: flink:1.7.2-scala_2.11
    ports:
      - "8081:8081"
      - "6123:6123"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./tmp/flink:/data/flink

  flink-taskmanager:
    image: flink:1.7.2-scala_2.11
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    volumes:
      - ./tmp/flink:/data/flink
    depends_on:
      - flink-jobmanager

  flink-deployer:
    build:
      context: flink-deployer/
    image: nielsdenissen/flink-deployer:master
    depends_on:
      - flink-jobmanager
      - flink-taskmanager
    # Deploy
    command:
      - "deploy"
      - "--file-name"
      - "/tmp/flink-stateful-wordcount-assembly-0.jar"
      - "--entry-class"
      - "WordCountStateful"
      - "--parallelism"
      - "2"
      - "--program-args"
      - "--intervalMs 1000"
    # Update
    # command:
    #   - "update"
    #   - "--job-name-base"
    #   - "Windowed WordCount"
    #   - "--file-name"
    #   - "/tmp/flink-stateful-wordcount-assembly-0.jar"
    #   - "--entry-class"
    #   - "WordCountStateful"
    #   - "--parallelism"
    #   - "2"
    #   - "--program-args"
    #   - "--intervalMs 1000"
    #   - "--savepoint-dir"
    #   - "/data/flink"
    volumes:
      - ./tmp/flink:/data/flink
      - ./flink-deployer/flink-sample-job/target/scala-2.11/:/tmp
    environment:
      - FLINK_BASE_URL=http://flink-jobmanager:8081
    links:
      - flink-jobmanager

networks:

  populous:
    driver: bridge
