filebeat.inputs:

  - type: log
    #change to true to enable this input configuration
    enabled: true
    paths:
      - /var/log/tweeter-streams/*/part-*
    fields:
      type: tweeter-streams
    fields_under_root: true

output.logstash:
      hosts: ["logstash:5044"]

#output.elasticsearch:
#    # Array of hosts to connect to.
#    hosts: ["elasticsearch:9200"]
#    username: "elastic"
#    password: "changeme"
